### ISSUE TITLE
Documentation update for running with docker-compose

### ISSUE THREAD

**Issue by phrreakk** [Backblaze/B2_Command_Line_Tool#1089]
I am trying to run the container in a standard docker-compose fashion, but I can't figure out how to do it correctly.

Sometimes it works with just authorize-account, even though the program says this is deprecated.

Here are two docker-compose.yml files, one works, one fails:

WORKS:
```
services:
  backblaze:
    image: backblazeit/b2:${APP_VERSION}
    command: authorize-account
    environment:
      B2_APPLICATION_KEY: ${B2_APPLICATION_KEY}
      B2_APPLICATION_KEY_ID: ${B2_APPLICATION_KEY_ID}
    volumes:
      - /var/ceph_data:/data
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        delay: 1h
      resources:
        limits: { cpus: '1' }
        reservations: { cpus: '0.025', memory: '16M' }
```
FAILS
```
services:
  backblaze:
    image: backblazeit/b2:${APP_VERSION}
    command: >
      sh -c "b2v4 account authorize &&  b2v4 sync --keep-days 7 --skip-newer /data/navidrome b2://swarm-apps-backups"
    environment:
      B2_APPLICATION_KEY: ${B2_APPLICATION_KEY}
      B2_APPLICATION_KEY_ID: ${B2_APPLICATION_KEY_ID}
    volumes:
      - /var/ceph_data:/data
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        delay: 1h
      resources:
        limits: { cpus: '1' }
        reservations: { cpus: '0.025', memory: '16M' }
```
In an env file, I have the 3 variables specified.

Thank you for your time

**Comment by phrreakk** [comment]
Apparently I was overthinking the command.  The below compose file is now working.

```
services:
  backblaze:
    image: backblazeit/b2:${APP_VERSION}
    command: b2v4 sync --keep-days 7 --skip-newer --exclude-dir-regex '(traefik)|(iso)|(runtime)' /data b2://swarm-apps-backups
    environment:
      B2_APPLICATION_KEY: ${B2_APPLICATION_KEY}
      B2_APPLICATION_KEY_ID: ${B2_APPLICATION_KEY_ID}
    volumes:
      - /var/ceph_data:/data
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        delay: 4h
      resources:
        limits: { cpus: '1' }
        reservations: { cpus: '0.025', memory: '16M' }
```
